function rotNedFromECEF = calcRotNedFromEcef(lat, lon)
    % Calculates the rotation matrix from ECEF to NED coordinates
    rotNedFromECEF = [-sin(lat) * cos(lon), -sin(lat) * sin(lon), cos(lat);...
                      -sin(lon),               cos(lon),               0;...
                      -cos(lat) * cos(lon), -cos(lat) * sin(lon), -sin(lat)];